version: 1

formatters:
  formatter:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
    datefmt: "%a, %d, %b %Y (%H:%M:%S)"

handlers:
  discord-console:
    class: logging.StreamHandler
    formatter: formatter
    level: WARNING
    stream: ext://sys.stdout
  console:
    class: logging.StreamHandler
    formatter: formatter
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: formatter
    filename: logs.log
    level: INFO
    encoding: "utf8"

loggers:
  Yami:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  discord:
    level: DEBUG
    handlers: [discord-console, file]
    propagate: no
root:
  level: WARNING
  handlers: [console]
